version: '3'

volumes:
  data:

services:

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: localdatabase
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
    networks:
      - global-default

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80
    volumes:
      - ./var/postgres:/var/lib/postgresql/data
    networks:
      - global-default

networks:
  global-default:
    external: true