version: "3."

services:

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    container_name: mysql
    networks:
      - global-default
    volumes:
      - ./var/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: localdatabase

networks:
  global-default:
    external: true