version: '3'

services:

  localstack:
    container_name: localstack
    image: localstack/localstack
    networks:
      - global-default
    ports:
      - 4566:4566
    environment:
      - SERVICES=s3,sqs,secretsmanager

networks:
  global-default:
    external: true