version: "3"
services:
  ninja:
    container_name: s3-ninja
    image: scireum/s3-ninja:6
    restart: always

    ports:
      - 9444:9000

    tmpfs:
      - "/home/sirius/data/test_bucket/:uid=2000,gid=2000"