version: '3'

volumes:
  data:

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    volumes:
      - data:/var/lib/mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "localdatabase"
    networks:
      - global-default

networks:
  global-default:
    external: true