version: '3'

services:

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    volumes:
      - ./var/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "localdatabase"
    networks:
      - global-default

networks:
  global-default:
    external: true